version: '3'
services:
  jupyter:
    build:
      context: containers/jupyter
    env_file:
      - config/jupyter.env
      - config/secrets.env
    ports:
      - "10000:8888"
    working_dir: /home/jovyan/source
    volumes:
      - ./source:/home/jovyan/source
      - ./nltk_data:/home/jovyan/nltk_data
