version: '3'
services:
  jupyter:
    build:
      context: docker/jupyter
    env_file:
      - docker/jupyter/jupyter.env
      - docker/jupyter/secrets.env
    ports:
      - "8888:8888"
    working_dir: /home/jovyan/source
    volumes:
      - ./source:/home/jovyan/source
      - ./nltk_data:/home/jovyan/nltk_data
